#!/usr/bin/env python3

import subprocess

print(
    round(float(
        subprocess.run(
            ['xbacklight', '-get'],
            stdout=subprocess.PIPE,
            encoding='UTF-8',
        ).stdout
    ))
)
