add_newline = true

format = """\
    $username\
    $hostname\
    $directory\
    $time\
    $python\
    $git_branch\
    $git_status\
    $git_state\
    $git_commit\
    $jobs\
    $cmd_duration\
    $status\
    $line_break\
    $character\
"""

[character]
disabled = false
format = "$symbol "
success_symbol = "[\\$](white)"
error_symbol = "[\\$](white)"

[username]
disabled = false
format = "[$user]($style) "
style_user = "bold yellow"
style_root = "bold red"
show_always = true

[time]
disabled = false
style = "dimmed bold white"
format = "[$time]($style) "
use_12hr = true

[directory]
disabled = false
style = "bold red"
truncation_length = 7
truncate_to_repo = false
format = "[$path]($style) "

[python]
disabled = false
style = "purple"
python_binary = "python3"
format = "[($virtualenv )]($style)"

[git_branch]
disabled = false
style = "white"
format = "[$symbol$branch ]($style)"

[git_status]
disabled = false
style = "white"
format = "[$all_status$ahead_behind ]($style)"
ahead = "↑"
behind = "↓"
deleted = "⨉"
diverged = "⇅"
modified = "·"
renamed = ""

[git_state]
disabled = false
style = "white"

[git_commit]
disabled = false
style = "white"

[jobs]
disabled = false
style = "blue"
threshold = 0
symbol = "+"

[cmd_duration]
disabled = false
style = "dimmed green"
format = "[$duration ]($style)"

[status]
disabled = false
style = "dimmed red"
format = "[$status ]($style)"
